name: "Project CryptoHelper CI/CD"
on:
  push:
jobs:
  build:
    runs-on: windows-latest    
      env:
        dotNetVersion: net6.0
        dotNetConfiguration: Release
        runtimeTarget: win-x86
    steps:
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.300'
    - name: Run automated unit and integration tests
      run: dotnet test CryptoHelper/UnitTests/UnitTests.csproj --configuration ${{ env.dotNetConfiguration }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@CryptoHelperV2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: CryptoHelper/UnitTests/TestResults/coverage.info 