name: "Project CryptoHelper CI/CD"

on:
  push:
    branches: [ "CryptoHelperV2", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CryptoHelper
    - name: Build
      run: dotnet build CryptoHelper --no-restore
    - name: Test
      run: dotnet test CryptoHelper/UnitTests/UnitTests.csproj --configuration ${{ env.dotNetConfiguration }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: CryptoHelper/UnitTests/TestResults/coverage.info 
